# -*- coding: utf-8 -*-
"""Conversion of videos from SD(640*40 px) to HD(1280* 720 px) videos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foW2vhJnCyxIieMkYUc-fmU737OewgCA
"""

!pip install diffusers
!pip install accelerate

import cv2
import numpy as np
import os
import torch
from diffusers import StableDiffusionInpaintPipeline

input_video_path = "market.mp4"
output_directory = "out_frames"

os.makedirs(output_directory, exist_ok=True)
cap = cv2.VideoCapture(input_video_path)
frame_count = 0
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    output_path = os.path.join(output_directory, f"frame_{frame_count}.jpg")
    cv2.imwrite(output_path, frame)
    frame_count += 1
    print(f"Processed frame {frame_count}")
cap.release()
cv2.destroyAllWindows()
print(f"{frame_count} frames extracted and saved to {output_directory}")

from google.colab.patches import cv2_imshow
input_image_path = '/content/output_frames/frame_0.jpg'
input_image = cv2.imread(input_image_path)
cv2_imshow(input_image)

new_image = np.zeros((720, 1280, 3), dtype=np.uint8)
center_x = int(new_image.shape[1] / 2) #640
center_y = int(new_image.shape[0] / 2) #360
half_width = int(input_image.shape[1] / 2) #320
half_height = int(input_image.shape[0] / 2) #240

new_image[center_y - half_height:center_y + half_height, center_x - half_width:center_x + half_width, 0:3] = input_image.copy()
cv2_imshow(new_image)

mask_image = np.ones((720, 1280, 3), dtype=np.uint8) * 255
mask_image[center_y - half_height:center_y + half_height, center_x - half_width:center_x + half_width, 0:3] = 0
cv2_imshow(mask_image)

pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-inpainting", torch_dtype=torch.float32
)

from diffusers import StableDiffusionPipeline
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float32
)

pipe.enable_attention_slicing()

prompt = "road, vehicles, buildings, trees, street lamps"
image = pipe(prompt=prompt, image=new_image, mask_image=mask_image).images[0]